import { Grid, GridItem, SkeletonCircle, SkeletonText } from '@chakra-ui/react'
import React from 'react'
export default function Loader() {
  return (
    <Grid w={"100%"} gap={"20px"} flexWrap={"wrap"}>
                      <GridItem
                          padding="6"
                          h={"auto"}
                          w={"100%"}
                          boxShadow="lg"
                          bg="white"
                        >
                        <SkeletonCircle
                          mt={'20px'}
                          size="10"
                          borderRadius={"10px"}
                          h={"200px"}
                          w={"100%"}
                        />
                          <SkeletonText
                            mt="4"
                            noOfLines={9}
                            spacing="4"
                            skeletonHeight="2"
                          />
                        </GridItem>
                      <GridItem
                          padding="6"
                          h={"auto"}
                          w={"100%"}
                          boxShadow="lg"
                          bg="white"
                        >
                        <SkeletonCircle
                          mt={'20px'}
                          size="10"
                          borderRadius={"10px"}
                          h={"200px"}
                          w={"100%"}
                        />
                          <SkeletonText
                            mt="4"
                            noOfLines={9}
                            spacing="4"
                            skeletonHeight="2"
                          />
                        </GridItem>
                      <GridItem
                          padding="6"
                          h={"auto"}
                          w={"100%"}
                          boxShadow="lg"
                          bg="white"
                        >
                        <SkeletonCircle
                          mt={'20px'}
                          size="10"
                          borderRadius={"10px"}
                          h={"200px"}
                          w={"100%"}
                        />
                          <SkeletonText
                            mt="4"
                            noOfLines={9}
                            spacing="4"
                            skeletonHeight="2"
                          />
                        </GridItem>
                      <GridItem
                          padding="6"
                          h={"auto"}
                          w={"100%"}
                          boxShadow="lg"
                          bg="white"
                        >
                        <SkeletonCircle
                          mt={'20px'}
                          size="10"
                          borderRadius={"10px"}
                          h={"200px"}
                          w={"100%"}
                        />
                          <SkeletonText
                            mt="4"
                            noOfLines={9}
                            spacing="4"
                            skeletonHeight="2"
                          />
                        </GridItem>
                      <GridItem
                          padding="6"
                          h={"auto"}
                          w={"100%"}
                          boxShadow="lg"
                          bg="white"
                        >
                        <SkeletonCircle
                          mt={'20px'}
                          size="10"
                          borderRadius={"10px"}
                          h={"200px"}
                          w={"100%"}
                        />
                          <SkeletonText
                            mt="4"
                            noOfLines={9}
                            spacing="4"
                            skeletonHeight="2"
                          />
                        </GridItem>
                  </Grid>
  )
}
